// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: tokens.jflex

/*-***
 *
 * This file defines a stand-alone lexical analyzer for a subset of the Pascal
 * programming language.  This is the same lexer that will later be integrated
 * with a CUP-based parser.  Here the lexer is driven by the simple Java test
 * program in ./PascalLexerTest.java, q.v.  See 330 Lecture Notes 2 and the
 * Assignment 2 writeup for further discussion.
 *
 */

/* USER CODE */

import java_cup.runtime.*;



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\0"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\0\1\17\12\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\0\32\27\1\30\1\31\1\32"+
    "\3\0\1\33\1\34\1\35\1\36\1\37\1\40\1\27"+
    "\1\41\1\42\2\27\1\43\1\27\1\44\1\45\1\46"+
    "\1\27\1\47\1\50\1\51\1\52\1\53\1\54\3\27"+
    "\1\55\1\56\1\57\1\60\6\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\1\1\23\12\21\1\24"+
    "\1\1\1\25\1\26\1\0\1\27\1\0\1\30\2\0"+
    "\1\31\1\32\1\0\1\33\1\34\1\35\1\36\2\0"+
    "\7\21\1\37\6\21\1\40\1\41\1\42\1\0\1\43"+
    "\7\21\1\44\6\21\1\43\1\45\1\46\1\21\1\47"+
    "\4\21\1\50\1\21\1\51\1\52\1\21\1\0\1\53"+
    "\1\54\1\55\1\56\1\57\1\21\1\60\1\21\1\61"+
    "\2\21\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\223\0\304\0\61\0\61"+
    "\0\61\0\365\0\61\0\u0126\0\61\0\u0157\0\61\0\61"+
    "\0\u0188\0\u01b9\0\u01ea\0\61\0\u021b\0\61\0\u024c\0\61"+
    "\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\u0405\0\u0436\0\61\0\u0467\0\61\0\61\0\142\0\61"+
    "\0\u0498\0\61\0\u04c9\0\u04fa\0\61\0\61\0\u052b\0\61"+
    "\0\61\0\61\0\61\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620"+
    "\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u021b\0\u0715\0\u0746\0\u0777"+
    "\0\u07a8\0\u07d9\0\u080a\0\61\0\61\0\u052b\0\u083b\0\61"+
    "\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u021b"+
    "\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u021b"+
    "\0\u021b\0\u0b1a\0\u021b\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u021b"+
    "\0\u0c0f\0\u021b\0\u021b\0\u0c40\0\u0ae9\0\u021b\0\u021b\0\u021b"+
    "\0\u021b\0\u0c71\0\u0ca2\0\u021b\0\u0cd3\0\u021b\0\u0d04\0\u0d35"+
    "\0\u021b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\25\1\31\1\32\1\25\1\33\1\34\1\25"+
    "\1\35\3\25\1\36\1\37\1\25\1\40\1\25\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\61\0\1\47\2\0"+
    "\3\47\1\50\1\47\1\0\20\47\1\51\27\47\7\0"+
    "\1\52\51\0\1\53\2\0\3\53\1\0\1\53\1\0"+
    "\20\53\1\54\27\53\14\0\1\55\62\0\1\56\42\0"+
    "\2\57\3\0\13\57\1\16\40\57\24\0\1\60\1\61"+
    "\57\0\1\62\60\0\1\63\54\0\1\25\6\0\1\25"+
    "\3\0\22\25\1\0\1\25\15\0\1\64\15\0\1\65"+
    "\47\0\1\25\6\0\1\25\3\0\12\25\1\66\7\25"+
    "\1\0\1\25\22\0\1\25\6\0\1\25\3\0\6\25"+
    "\1\67\1\25\1\70\11\25\1\0\1\25\22\0\1\25"+
    "\6\0\1\25\3\0\10\25\1\71\11\25\1\0\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\1\72\6\25\1\73"+
    "\1\74\11\25\1\0\1\25\22\0\1\25\6\0\1\25"+
    "\3\0\5\25\1\75\3\25\1\76\10\25\1\0\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\14\25\1\77\5\25"+
    "\1\0\1\25\22\0\1\25\6\0\1\25\3\0\4\25"+
    "\1\100\15\25\1\0\1\25\22\0\1\25\6\0\1\25"+
    "\3\0\14\25\1\101\5\25\1\0\1\25\22\0\1\25"+
    "\6\0\1\25\3\0\12\25\1\102\7\25\1\0\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\6\25\1\103\13\25"+
    "\1\0\1\25\60\0\1\104\2\0\2\47\3\0\54\47"+
    "\10\0\1\105\50\0\2\53\3\0\54\53\20\0\1\106"+
    "\40\0\13\64\1\107\45\64\2\65\1\110\2\0\54\65"+
    "\20\0\1\25\6\0\1\25\3\0\12\25\1\111\7\25"+
    "\1\0\1\25\22\0\1\25\6\0\1\25\3\0\1\112"+
    "\21\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\1\113\21\25\1\0\1\25\22\0\1\25\6\0\1\25"+
    "\3\0\15\25\1\114\4\25\1\0\1\25\22\0\1\25"+
    "\6\0\1\25\3\0\10\25\1\115\11\25\1\0\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\11\25\1\116\10\25"+
    "\1\0\1\25\22\0\1\25\6\0\1\25\3\0\12\25"+
    "\1\117\7\25\1\0\1\25\22\0\1\25\6\0\1\25"+
    "\3\0\16\25\1\120\3\25\1\0\1\25\22\0\1\25"+
    "\6\0\1\25\3\0\7\25\1\121\12\25\1\0\1\25"+
    "\22\0\1\25\6\0\1\25\3\0\1\122\15\25\1\123"+
    "\3\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\17\25\1\124\2\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\7\25\1\125\12\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\7\25\1\126\12\25\1\0"+
    "\1\25\33\0\1\127\47\0\1\25\6\0\1\25\3\0"+
    "\10\25\1\130\11\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\14\25\1\131\5\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\15\25\1\132\4\25\1\0"+
    "\1\25\22\0\1\25\6\0\1\25\3\0\4\25\1\133"+
    "\15\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\15\25\1\134\4\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\1\135\21\25\1\0\1\25\22\0\1\25"+
    "\6\0\1\25\3\0\1\136\21\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\11\25\1\137\10\25\1\0"+
    "\1\25\22\0\1\25\6\0\1\25\3\0\3\25\1\140"+
    "\16\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\17\25\1\141\2\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\4\25\1\142\15\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\3\25\1\143\16\25\1\0"+
    "\1\25\22\0\1\25\6\0\1\25\3\0\10\25\1\144"+
    "\11\25\1\0\1\25\2\0\13\64\1\0\15\64\1\145"+
    "\27\64\20\0\1\25\6\0\1\25\3\0\15\25\1\146"+
    "\4\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\4\25\1\147\15\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\10\25\1\150\11\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\16\25\1\151\3\25\1\0"+
    "\1\25\22\0\1\25\6\0\1\25\3\0\16\25\1\152"+
    "\3\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\14\25\1\153\5\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\4\25\1\154\15\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\10\25\1\155\11\25\1\0"+
    "\1\25\22\0\1\25\6\0\1\25\3\0\11\25\1\156"+
    "\10\25\1\0\1\25\22\0\1\25\6\0\1\25\3\0"+
    "\7\25\1\157\12\25\1\0\1\25\22\0\1\25\6\0"+
    "\1\25\3\0\11\25\1\160\10\25\1\0\1\25\22\0"+
    "\1\25\6\0\1\25\3\0\4\25\1\161\15\25\1\0"+
    "\1\25\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3430];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\3\11\1\1\1\11\1\1\1\11"+
    "\1\1\2\11\3\1\1\11\1\1\1\11\1\1\1\11"+
    "\12\1\1\11\1\1\2\11\1\0\1\11\1\0\1\11"+
    "\2\0\2\11\1\0\4\11\2\0\16\1\2\11\1\1"+
    "\1\0\1\11\34\1\1\0\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

Symbol newSym(int tokenId) {
    return new Symbol(tokenId, yyline, yycolumn);
}

Symbol newSym(int tokenId, Object value) {
    return new Symbol(tokenId, yyline, yycolumn, value);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Illegal char, '" + yytext() + "' line: " + yyline + ", column: " + yychar);
            }
            // fall through
          case 51: break;
          case 2:
            { /* Ignore whitespace. */
            }
            // fall through
          case 52: break;
          case 3:
            { return newSym(sym.L_PAREN, new String(yytext()) );
            }
            // fall through
          case 53: break;
          case 4:
            { return newSym(sym.R_PAREN, new String(yytext()) );
            }
            // fall through
          case 54: break;
          case 5:
            { return newSym(sym.MULTIPLY_OP, new String(yytext()) );
            }
            // fall through
          case 55: break;
          case 6:
            { return newSym(sym.PLUS_OP, new String(yytext()) );
            }
            // fall through
          case 56: break;
          case 7:
            { return newSym(sym.COMMA, new String(yytext()) );
            }
            // fall through
          case 57: break;
          case 8:
            { return newSym(sym.MINUS_OP, new String(yytext()) );
            }
            // fall through
          case 58: break;
          case 9:
            { return newSym(sym.DIVIDE_OP, new String(yytext()) );
            }
            // fall through
          case 59: break;
          case 10:
            { return newSym(sym.INTLIT, new Integer(yytext()));
            }
            // fall through
          case 60: break;
          case 11:
            { return newSym(sym.COLON, new String(yytext()) );
            }
            // fall through
          case 61: break;
          case 12:
            { return newSym(sym.SEMI_COLON, new String(yytext()) );
            }
            // fall through
          case 62: break;
          case 13:
            { return newSym(sym.LT_OP, new String(yytext()) );
            }
            // fall through
          case 63: break;
          case 14:
            { return newSym(sym.ASSIGN, new String(yytext()) );
            }
            // fall through
          case 64: break;
          case 15:
            { return newSym(sym.GT_OP, new String(yytext()) );
            }
            // fall through
          case 65: break;
          case 16:
            { return newSym(sym.QUESTION, new String(yytext()) );
            }
            // fall through
          case 66: break;
          case 17:
            { return newSym(sym.ID, yytext());
            }
            // fall through
          case 67: break;
          case 18:
            { return newSym(sym.L_SQBRAC, new String(yytext()) );
            }
            // fall through
          case 68: break;
          case 19:
            { return newSym(sym.R_SQBRAC, new String(yytext()) );
            }
            // fall through
          case 69: break;
          case 20:
            { return newSym(sym.L_CURLY, new String(yytext()) );
            }
            // fall through
          case 70: break;
          case 21:
            { return newSym(sym.R_CURLY, new String(yytext()) );
            }
            // fall through
          case 71: break;
          case 22:
            { return newSym(sym.BIN_NEG, new String(yytext()) );
            }
            // fall through
          case 72: break;
          case 23:
            { return newSym(sym.STRINGLIT, new String(yytext()));
            }
            // fall through
          case 73: break;
          case 24:
            { return newSym(sym.AND_OP, new String(yytext()) );
            }
            // fall through
          case 74: break;
          case 25:
            { return newSym(sym.AUTO_INCREMENT, new String(yytext()) );
            }
            // fall through
          case 75: break;
          case 26:
            { return newSym(sym.AUTO_DECREMENT, new String(yytext()) );
            }
            // fall through
          case 76: break;
          case 27:
            { return newSym(sym.LTE_OP, new String(yytext()) );
            }
            // fall through
          case 77: break;
          case 28:
            { return newSym(sym.NOT_EQUAL_OP, new String(yytext()) );
            }
            // fall through
          case 78: break;
          case 29:
            { return newSym(sym.EQUAL_OP, new String(yytext()) );
            }
            // fall through
          case 79: break;
          case 30:
            { return newSym(sym.GTE_OP, new String(yytext()) );
            }
            // fall through
          case 80: break;
          case 31:
            { return newSym(sym.IF, new String(yytext()) );
            }
            // fall through
          case 81: break;
          case 32:
            { return newSym(sym.OR_OP, new String(yytext()) );
            }
            // fall through
          case 82: break;
          case 33:
            { return newSym(sym.CHARLIT, new Character(yytext().charAt(1)));
            }
            // fall through
          case 83: break;
          case 34:
            { return newSym(sym.FLOATLIT, new Float(yytext()));
            }
            // fall through
          case 84: break;
          case 35:
            { /* Comment */
            }
            // fall through
          case 85: break;
          case 36:
            { return newSym(sym.INT, new String(yytext()) );
            }
            // fall through
          case 86: break;
          case 37:
            { return newSym(sym.BOOL, new String(yytext()) );
            }
            // fall through
          case 87: break;
          case 38:
            { return newSym(sym.CHAR, new String(yytext()) );
            }
            // fall through
          case 88: break;
          case 39:
            { return newSym(sym.ELSE, new String(yytext()) );
            }
            // fall through
          case 89: break;
          case 40:
            { return newSym(sym.READ, new String(yytext()) );
            }
            // fall through
          case 90: break;
          case 41:
            { return newSym(sym.TRUE, new String(yytext()) );
            }
            // fall through
          case 91: break;
          case 42:
            { return newSym(sym.VOID, new String(yytext()) );
            }
            // fall through
          case 92: break;
          case 43:
            { return newSym(sym.CLASS, new String(yytext()) );
            }
            // fall through
          case 93: break;
          case 44:
            { return newSym(sym.FALSE, new String(yytext()) );
            }
            // fall through
          case 94: break;
          case 45:
            { return newSym(sym.FINAL, new String(yytext()) );
            }
            // fall through
          case 95: break;
          case 46:
            { return newSym(sym.FLOAT, new String(yytext()) );
            }
            // fall through
          case 96: break;
          case 47:
            { return newSym(sym.PRINT, new String(yytext()) );
            }
            // fall through
          case 97: break;
          case 48:
            { return newSym(sym.WHILE, new String(yytext()) );
            }
            // fall through
          case 98: break;
          case 49:
            { return newSym(sym.RETURN, new String(yytext()) );
            }
            // fall through
          case 99: break;
          case 50:
            { return newSym(sym.PRINTLINE, new String(yytext()) );
            }
            // fall through
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
