
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LT_OP = 44;
  public static final int CHAR = 22;
  public static final int STRINGLIT = 47;
  public static final int L_PAREN = 4;
  public static final int R_PAREN = 5;
  public static final int BIN_NEG = 28;
  public static final int INT = 21;
  public static final int EQUAL_OP = 39;
  public static final int INTLIT = 49;
  public static final int GTE_OP = 41;
  public static final int BOOL = 23;
  public static final int COMMA = 8;
  public static final int CLASS = 15;
  public static final int OR_OP = 38;
  public static final int GT_OP = 43;
  public static final int ASSIGN = 45;
  public static final int IF = 13;
  public static final int ID = 46;
  public static final int AND_OP = 37;
  public static final int EOF = 0;
  public static final int PREFIXPLUS_OP = 31;
  public static final int RETURN = 18;
  public static final int PRINTLINE = 17;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int L_CURLY = 2;
  public static final int L_SQBRAC = 6;
  public static final int R_CURLY = 3;
  public static final int SEMI_COLON = 10;
  public static final int AUTO_INCREMENT = 26;
  public static final int VOID = 20;
  public static final int PLUS_OP = 30;
  public static final int FLOATLIT = 50;
  public static final int MINUS_OP = 29;
  public static final int DIVIDE_OP = 34;
  public static final int CHARLIT = 48;
  public static final int NOT_EQUAL_OP = 40;
  public static final int COLON = 9;
  public static final int AUTO_DECREMENT = 27;
  public static final int ELSE = 14;
  public static final int READ = 25;
  public static final int FINAL = 19;
  public static final int WHILE = 12;
  public static final int FLOAT = 24;
  public static final int MULTIPLY_OP = 33;
  public static final int QUESTION = 11;
  public static final int PREFIXMINUS_OP = 32;
  public static final int FALSE = 36;
  public static final int LTE_OP = 42;
  public static final int PRINT = 16;
  public static final int R_SQBRAC = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "L_CURLY",
  "R_CURLY",
  "L_PAREN",
  "R_PAREN",
  "L_SQBRAC",
  "R_SQBRAC",
  "COMMA",
  "COLON",
  "SEMI_COLON",
  "QUESTION",
  "WHILE",
  "IF",
  "ELSE",
  "CLASS",
  "PRINT",
  "PRINTLINE",
  "RETURN",
  "FINAL",
  "VOID",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "READ",
  "AUTO_INCREMENT",
  "AUTO_DECREMENT",
  "BIN_NEG",
  "MINUS_OP",
  "PLUS_OP",
  "PREFIXPLUS_OP",
  "PREFIXMINUS_OP",
  "MULTIPLY_OP",
  "DIVIDE_OP",
  "TRUE",
  "FALSE",
  "AND_OP",
  "OR_OP",
  "EQUAL_OP",
  "NOT_EQUAL_OP",
  "GTE_OP",
  "LTE_OP",
  "GT_OP",
  "LT_OP",
  "ASSIGN",
  "ID",
  "STRINGLIT",
  "CHARLIT",
  "INTLIT",
  "FLOATLIT"
  };
}

